### ISSUE TITLE
UnsupportedOperationException

### ISSUE THREAD

**Issue by IAmJulianAcosta** [YunlongYang/flutter_update#5]
Hi, I'm getting this error, do you know what is happening?

```
E/AndroidRuntime(29154): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.documentsui/com.android.documentsui.picker.PickActivity}: java.lang.UnsupportedOperationException: Unexpected action type: 0
E/AndroidRuntime(29154): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
E/AndroidRuntime(29154): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/AndroidRuntime(29154): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/AndroidRuntime(29154): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(29154): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(29154): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/AndroidRuntime(29154): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(29154): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(29154): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(29154): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29154): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(29154): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(29154): Caused by: java.lang.UnsupportedOperationException: Unexpected action type: 0
E/AndroidRuntime(29154): 	at com.android.documentsui.picker.ActionHandler.loadDefaultLocation(ActionHandler.java:239)
E/AndroidRuntime(29154): 	at com.android.documentsui.picker.ActionHandler.onLastAccessedStackLoaded(ActionHandler.java:190)
E/AndroidRuntime(29154): 	at com.android.documentsui.picker.ActionHandler.initLoadLastAccessedStack(ActionHandler.java:176)
E/AndroidRuntime(29154): 	at com.android.documentsui.picker.ActionHandler.initLocation(ActionHandler.java:135)
E/AndroidRuntime(29154): 	at com.android.documentsui.picker.PickActivity.onCreate(PickActivity.java:161)
E/AndroidRuntime(29154): 	at android.app.Activity.performCreate(Activity.java:8000)
E/AndroidRuntime(29154): 	at android.app.Activity.performCreate(Activity.java:7984)
E/AndroidRuntime(29154): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/AndroidRuntime(29154): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/AndroidRuntime(29154): 	... 11 more
```

**Comment by YunlongYang** [comment]
Your problem does not seem to be caused by this project。
